name: "Update Warps"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

permissions:
  contents: write

env:
  message: "update"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.7.0
      - run: "node warp-data/get-warp-data.js"
      - run: echo "message=Warp update @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: EndBug/add-and-commit@fc1cf1dd8747466e3313305ba0d26460c62a7e59 # v11.1.0
        with:
          default_author: github_actions
          message: ${{ env.message }}
